# This is the network config written by 'subiquity'
network:
  ethernets:
    enp1s0:
      dhcp4: true
    enp6s0:
      dhcp4: no
      addresses: [10.200.200.199/24]
      nameservers:
              addresses: [10.200.200.199]
  version: 2
