# This is the network config written by 'subiquity'
network:
  ethernets:
    enp1s0:
      dhcp4: no
      addresses: [10.20.20.2/24]
      gateway4: 10.20.20.254
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
  version: 2

