# This is the network config written by 'subiquity'
network:
  ethernets:
    enp1s0:
      dhcp4: true
    enp6s0:
      dhcp4: no
      addresses: [10.10.10.254/24]
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
    enp7s0:
      dhcp4: no
      addresses: [10.20.20.254/24]
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
  version: 2
